
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-feign-client

feign:
  hystrix:
    enabled: true

#springboot2.0. 的配置项为：
#actuator端口
management:
  server:
    port: 9002
  endpoints:
    web:
#      base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点