
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-turbine

#springboot2.0. \u7684\u914D\u7F6E\u9879\u4E3A\uFF1A
#actuator\u7AEF\u53E3
management:
#  server:
#    port: 9007
  endpoints:
    web:
#      base-path: /monitor #\u4FEE\u6539\u8BBF\u95EE\u8DEF\u5F84  2.0\u4E4B\u524D\u9ED8\u8BA4\u662F/   2.0\u9ED8\u8BA4\u662F /actuator  \u53EF\u4EE5\u901A\u8FC7\u8FD9\u4E2A\u5C5E\u6027\u503C\u4FEE\u6539
      exposure:
        include: '*'  #\u5F00\u653E\u6240\u6709\u9875\u9762\u8282\u70B9  \u9ED8\u8BA4\u53EA\u5F00\u542F\u4E86health\u3001info\u4E24\u4E2A\u8282\u70B9

turbine:
  aggregator:
    cluster-config: default  # \u9700\u8981\u76D1\u63A7\u7684\u670D\u52A1\u96C6\u7FA4\u540D
  app-config: eureka-feign-client,eureka-ribbon-client  #\u9700\u8981\u76D1\u63A7\u7684\u670D\u52A1\u540D
  cluster-name-expression: new String("default")
#  instanceUrlSuffix:
#      default: actuator/hystrix.stream    #key\u662FclusterConfig\u96C6\u7FA4\u7684\u540D\u5B57\uFF0Cvalue\u662Fhystrix\u76D1\u63A7\u7684\u540E\u7F00\uFF0Cspringboot2.0\u4E3Aactuator/hystrix.stream


